local opts = {
	autochdir = false,
	background = "dark",
	backspace = "indent,eol,start",
	backup = false,
	clipboard = "unnamedplus",
	cmdheight = 1,
	colorcolumn = "0",
	compatible = false,
	completeopt = { "menuone", "noselect" },
	cursorline = false,
	errorbells = false,
	expandtab = true,
	fileencoding = "utf-8",
	guifont = "FiraMono Nerd Font:h17",
	hidden = true,
	ignorecase = true,
	laststatus = 2,
	modifiable = true,
	mouse = "a",
	number = true,
	pumheight = 10,
	relativenumber = false,
	scrolloff = 8,
	shiftwidth = 4,
	showcmd = true,
	showmode = false,
	showtabline = 2,
	sidescrolloff = 8,
	signcolumn = "yes",
	smartcase = true,
	smartindent = true,
	softtabstop = 4,
	splitbelow = true,
	splitright = true,
	swapfile = false,
	syntax = "ON",
	tabstop = 4,
	termguicolors = true,
	title = true,
	undodir = os.getenv("HOME") .. "/.vim/undodir",
	undofile = true,
	wrap = true,
}

for k, v in pairs(opts) do
	vim.opt[k] = v
end
