return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
		"windwp/nvim-ts-autotag",
	},
	lazy = false,
	config = function()
		require("nvim-treesitter.configs").setup({
			build = ":TSUpdate",
			indent = { enable = true },
			autotag = { enable = true },
			event = {
				"BufReadPre",
				"BufNewFile",
			},
			ensure_installed = {
				"arduino",
				"bash",
				"c",
				"comment",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"gitignore",
				"hcl",
				"html",
				"ini",
				"javascript",
				"jsdoc",
				"json",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"php",
				"phpdoc",
				"python",
				"regex",
				"scss",
				"sql",
				"ssh_config",
				"terraform",
				"toml",
				"vim",
				"vue",
				"query",
				"xml",
				"yaml",
			},
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = true,
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<BS>",
				},
			},
			context_commentstring = {
				enable = true,
				enable_autocmd = false,
			},
		})
	end,
}
